"""add paper_account_snapshots for QFRS

Revision ID: 320128e72164
Revises: 9d4a38ea92bd
Create Date: 2026-10-01 07:32:47.210175

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '320128e72164'
down_revision: Union[str, Sequence[str], None] = '9d4a38ea92bd'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
