"""add paper_account_snapshots for QFRS

Revision ID: 9d4a38ea92bd
Revises: 0011
Create Date: 2026-10-01 07:32:03.712048

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '9d4a38ea92bd'
down_revision: Union[str, Sequence[str], None] = '0011'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('paper_account_snapshots',
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('snap_date', sa.Date(), nullable=False),
    sa.Column('cash', sa.Float(), nullable=False),
    sa.Column('position_value', sa.Float(), nullable=False),
    sa.Column('total_equity', sa.Float(), nullable=False),
    sa.Column('daily_return', sa.Float(), nullable=False),
    sa.Column('position_count', sa.Integer(), nullable=False),
    sa.Column('snapshot_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_paper_account_snapshots_snap_date'), 'paper_account_snapshots', ['snap_date'], unique=False)
    op.create_index(op.f('ix_paper_account_snapshots_user_id'), 'paper_account_snapshots', ['user_id'], unique=False)
    op.create_index('ix_paper_snap_user_date', 'paper_account_snapshots', ['user_id', 'snap_date'], unique=True)
    op.drop_index(op.f('ix_api_keys_user'), table_name='api_keys')
    op.drop_index(op.f('ix_portfolio_user_id'), table_name='portfolio')
    op.drop_index(op.f('ix_users_client_id'), table_name='users')
    op.create_unique_constraint(None, 'users', ['client_id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    # WARNING: constraint name is None; this directive will fail as
    # rendered.  Add a name, or use a naming convention; see
    # https://alembic.sqlalchemy.org/en/latest/naming.html
    op.drop_constraint('users_client_id_key', 'users', type_='unique')
    op.create_index(op.f('ix_users_client_id'), 'users', ['client_id'], unique=True)
    op.create_index(op.f('ix_portfolio_user_id'), 'portfolio', ['user_id'], unique=False)
    op.create_index(op.f('ix_api_keys_user'), 'api_keys', ['user_id'], unique=False)
    op.drop_index('ix_paper_snap_user_date', table_name='paper_account_snapshots')
    op.drop_index(op.f('ix_paper_account_snapshots_user_id'), table_name='paper_account_snapshots')
    op.drop_index(op.f('ix_paper_account_snapshots_snap_date'), table_name='paper_account_snapshots')
    op.drop_table('paper_account_snapshots')
    # ### end Alembic commands ###
