"""add asset breakdown to paper snapshots

Revision ID: afeb0a91df5a
Revises: 320128e72164
Create Date: 2026-10-02 06:44:10.426588

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'afeb0a91df5a'
down_revision: Union[str, Sequence[str], None] = '320128e72164'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('paper_account_snapshots',
        sa.Column('stock_value', sa.Float(), nullable=False, server_default='0'))
    op.add_column('paper_account_snapshots',
        sa.Column('crypto_value', sa.Float(), nullable=False, server_default='0'))
    op.add_column('paper_account_snapshots',
        sa.Column('alt_value', sa.Float(), nullable=False, server_default='0'))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('paper_account_snapshots', 'alt_value')
    op.drop_column('paper_account_snapshots', 'crypto_value')
    op.drop_column('paper_account_snapshots', 'stock_value')
    # ### end Alembic commands ###
